export const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8080/api/v1.0";
const CLOUDINARY_CLOUD_NAME = "dhadf5h7j";

export const API_ENDPOINTS = {
    LOGIN: "/login",
    REGISTER: "/register",
    GET_USER_INFO: "/profile",
    GET_ALL_CATEGORIES: "/categories",
    ADD_CATEGORY: "/categories",
    UPDATE_CATEGORY: (categoryId) => `/categories/${categoryId}`,
    GET_ALL_INCOMES: "/incomes",
    CATEGORY_BY_TYPE: (type) => `/categories/${type}`,
    ADD_INCOME: "/incomes",
    DELETE_INCOME: (incomeId) => `/incomes/${incomeId}`,
    INCOME_EXCEL_DOWNLOAD: "excel/download/income",
    EMAIL_INCOME: "/email/income-excel",
    GET_ALL_EXPENSE: "/expenses",
    ADD_EXPENSE: "/expenses",
    DELETE_EXPENSE: (expenseId) => `/expenses/${expenseId}`,
    EXPENSE_EXCEL_DOWNLOAD: "excel/download/expense",
    EMAIL_EXPENSE: "/email/expense-excel",
    APPLY_FILTERS: "/filter",
    DASHBOARD_DATA: "/dashboard",
    UPLOAD_IMAGE: `https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`,
    AI_ADVICE: "/ai/advice",
    AI_INSIGHTS: "/ai/insights",
    BUDGETS: "/budgets",
    SAVINGS_GOALS: "/savings-goals",
    GOAL_CONTRIBUTIONS: (goalId) => `/savings-goals/${goalId}/contributions`,
    RECURRING_TRANSACTIONS: "/recurring-transactions",
    PROCESS_RECURRING_DUE: "/recurring-transactions/process-due",
    BILL_REMINDERS: "/bill-reminders",
    UPCOMING_BILL_REMINDERS: "/bill-reminders/upcoming",
    MONEY_PLAN_SUMMARY: "/money-plan/summary",
    MONTHLY_ANALYTICS: "/analytics/monthly",
    FAMILIES: "/families",
    FAMILY_DASHBOARD: (familyId) => `/families/${familyId}/dashboard`,
    FAMILY_MEMBERS: (familyId) => `/families/${familyId}/members`,
    FAMILY_TRANSFERS: (familyId) => `/families/${familyId}/transfers`,
    FRIENDS_DASHBOARD: "/friends/dashboard",
    FRIENDS: "/friends",
    FRIEND_STATUS: (friendId) => `/friends/${friendId}/status`,
    FRIEND_GROUPS: "/friends/groups",
    FRIEND_EXPENSES: "/friends/expenses",
    FRIEND_SETTLEMENTS: "/friends/settlements",
    FRIEND_REMINDERS: "/friends/reminders",
    FRIEND_EXPENSE_COMMENTS: (expenseId) => `/friends/expenses/${expenseId}/comments`,
}

